/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.PatientController;



/**
 *
 * @author user
 */
public class AppointementScheduling extends javax.swing.JFrame {

    /**
     * Creates new form AppointementScheduling
     */
    public AppointementScheduling() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        maleRBtn = new javax.swing.JCheckBox();
        femaleRBtn = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        DR_vimal = new javax.swing.JCheckBox();
        Dr_kumar = new javax.swing.JCheckBox();
        DR_raja = new javax.swing.JCheckBox();
        DR_arun = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dis = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mAKE A appOINTMENT IN HL (3)_1.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 126, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("PATIENT NAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 230, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 280, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 279, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("PATIENT GENDER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        maleRBtn.setText("male");
        getContentPane().add(maleRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        femaleRBtn.setText("female");
        getContentPane().add(femaleRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("DOCTOR NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        DR_vimal.setText("DR_vimal");
        getContentPane().add(DR_vimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 100, -1));

        Dr_kumar.setText("DR_arun");
        getContentPane().add(Dr_kumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 90, -1));

        DR_raja.setText("DR_raja");
        getContentPane().add(DR_raja, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 90, -1));

        DR_arun.setText("DR_kumar");
        getContentPane().add(DR_arun, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 100, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("DESCRIPTION");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        dis.setColumns(20);
        dis.setRows(5);
        jScrollPane1.setViewportView(dis);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 353, 90));

        submit.setText("submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 585, 100, 40));

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, 110, 50));

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 100, 40));

        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText(" PATIENT CONTACT NUMBER");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        getContentPane().add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 280, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add a subheading.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String gender = null;
             if (maleRBtn.isSelected()) {
             gender = "Male";
             } else if (femaleRBtn.isSelected()) {
             gender = "Female";
             }
         String appointment = null;

        if (DR_arun.isSelected()) {
        appointment = "DR_arun";
       } else if (DR_vimal.isSelected()) {
           appointment = "DR_vimal";
          } else if (DR_raja.isSelected()) {
       appointment = "DR_raja";
        } else if (Dr_kumar.isSelected()) {
    appointment = "DR_kumar";
        }
           PatientController.Form(name.getText(), number.getText(), dis.getText(), gender,appointment );
            clearField();

    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
      maleRBtn.setSelected(false);
      femaleRBtn.setSelected(false);
      Dr_kumar.setSelected(false);
      DR_vimal.setSelected(false);
      DR_raja.setSelected(false);
      DR_arun.setSelected(false);
    }//GEN-LAST:event_clearActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        new view.user_interface().setVisible(true);
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointementScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointementScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointementScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointementScheduling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointementScheduling().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox DR_arun;
    private javax.swing.JCheckBox DR_raja;
    private javax.swing.JCheckBox DR_vimal;
    private javax.swing.JCheckBox Dr_kumar;
    private javax.swing.JButton Exit;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton clear;
    private javax.swing.JTextArea dis;
    private javax.swing.JCheckBox femaleRBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox maleRBtn;
    private javax.swing.JTextField name;
    private javax.swing.JTextField number;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    private void clearField() {
        name.setText("");
        number.setText("");
        maleRBtn.setSelected(true);
        Dr_kumar.setSelected(true);
        dis.setText("");
    }
}
