/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Assigncontroller;
import controller.PatientController;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import model.DBConnection;
import model.DBSearch;

/**
 *
 * @author user
 */
public class ASSIGNDOCTOR extends javax.swing.JFrame {

    /**
     * Creates new form addDignosis
     */
    public ASSIGNDOCTOR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        mnCMB = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        statusCMB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Update patient");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 524, -1, 49));

        jButton4.setText("Clear ");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 524, 103, 49));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("doctor name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 150, -1));

        jButton6.setText("Exit");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 524, 92, 49));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Treatement type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("available status");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 180, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("time-period");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 132, -1));

        jButton1.setText("ASSIGN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 524, -1, 49));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 451, 230, 40));

        jButton5.setText("Back to DashBord");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "name", "number", "gender", "Doctor", "discription"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 491, 100));

        jButton2.setText("view the appointment details made by Patient ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 69, 328, 51));

        mnCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DR_arun", "DR_vimal", "DR_raja", "DR_kumar" }));
        mnCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCMBActionPerformed(evt);
            }
        });
        getContentPane().add(mnCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 199, 222, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronic Health Records ", "Telemedicine", "Clinical Decision Support", "Appointment Management", "Lab Management" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 271, 222, 50));

        statusCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " AVAILABEL", "NOT AVAILABEL" }));
        statusCMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusCMBActionPerformed(evt);
            }
        });
        getContentPane().add(statusCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(787, 358, 230, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Add a subheading (4).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 660));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
    dtm.setRowCount(0); // Clear existing rows

    try (ResultSet r = new DBSearch().searchpatient()) {
        while (r.next()) {
            Vector<String> v = new Vector<>();
            v.add(r.getString("PATIENT_NAME"));
            v.add(r.getString("PATIENT_NUMBER"));
            v.add(r.getString("PATIENT_GENDER"));
            v.add(r.getString("DOCTOR_NAME"));
            v.add(r.getString("DESCRIPTION"));
            dtm.addRow(v);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void statusCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusCMBActionPerformed
        String status = (String) statusCMB.getSelectedItem();// TODO add your handling code here:
    }//GEN-LAST:event_statusCMBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    
    String DNAME =mnCMB.getSelectedItem().toString();
    String TRty =jComboBox2.getSelectedItem().toString();
    String status =statusCMB.getSelectedItem().toString();
    String time = jTextField4.getText();
    


  Assigncontroller.ASSIGNDOCT(DNAME, TRty, status, time);
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mnCMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCMBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnCMBActionPerformed
    
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASSIGNDOCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASSIGNDOCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASSIGNDOCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASSIGNDOCTOR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ASSIGNDOCTOR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JComboBox<String> mnCMB;
    private javax.swing.JComboBox<String> statusCMB;
    // End of variables declaration//GEN-END:variables
}
